service: serverless-scheduler-sample

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 256
  timeout: 6
  stage: ${opt:stage, 'dev'}
  region: ap-south-1
  lambdaHashingVersion: 20201221
  iam:
    role: IamLambdaExecutionRole

functions:
  scheduler-test:
    handler: src/handler.handler

resources: ${file(resources/resources.yml)}
